#!/bin/sh

PIDID=`pgrep -f "judged.php"`
DIR_OF_JUDGEDPHP=$(dirname $0)
RUN_CMD="sudo -u www-data php7.2 ${DIR_OF_JUDGEDPHP}/judged.php"
LOG_DIR='/var/log/onlinejudge/'

#make logging directory
mkdir -p ${LOG_DIR}

# Restart
if ! [ -z $1 ]; then
    if [ $1 = "restart" ]; then
        if ! [ -z ${PIDID} ]; then
            echo "Restarting judged.php..."
            kill ${PIDID}
	    ${RUN_CMD} >> "${LOG_DIR}judged.log" 2>&1
            exit 0
        else
            echo "judged.php PID not found"
        fi
    fi
fi

if ! [ -z ${PIDID} ]; then
    echo "judged.php is already running (pid $PIDID)"
else
    echo "judged.php is not running, starting it..."
    ${RUN_CMD} >> "${LOG_DIR}judged.log" 2>&1
fi
