language: php
before_install:
  - travis_retry composer self-update
  - composer install

script: 
- phpunit --exclude-group FITS --bootstrap vendor/autoload.php tests
- ./vendor/bin/phpunit --coverage-clover ./tests/logs/clover.xml

after_script:
- php vendor/bin/coveralls -v
- php scripts/coveralls -v --exclude-no-stmt
