#!/bin/sh

PIDID=`pgrep -f "judged.php"`

#stop judge
if ! [ -z ${PIDID} ]; then
    echo "judged.php is running (pid $PIDID).\nStopping judge..."
    kill -9 ${PIDID}
else
    echo "judged.php is not running."
fi
